test-requirements.txt: DownRev Scapy to 2.4.4 (#3869)
In order to avoid this exception with 'send(fuzz(...))' usage:
---
  File "/venv/lib/python3.7/site-packages/scapy/arch/linux.py", line 605, in send
    self.outs.bind(sdto)
TypeError: argument 1 must be str, not NetworkInterface
---

Which is seen in the following integration tests:
* FaucetUntaggedIPv4ControlPlaneFuzzTest
* FaucetUntaggedIPv6ControlPlaneFuzzTest